swagger: '2.0'
info:
  description: BitWaves 后端接口文档
  version: 1.0.0
  title: BitWaves Web API Docs
  contact:
    email: msrlancern@126.com

tags:
  - name: users
    description: 用于访问用户数据的 API
  - name: auth
    description: 用于用户身份验证的 API

paths:
  /users:
    post:
      summary: 创建一个新用户
      description: 创建一个新用户
      tags:
        - users
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: data
          required: true
          schema:
            type: object
            required:
              - username
              - password
              - phone
            properties:
              username:
                description: 用户名，长度至少为3个字符
                type: string
                example: Lancern
              password:
                description: 密码，长度至少为6个字符
                type: string
                example: hello_world
              phone:
                description: 手机号，应由11个数字组成
                type: string
                example: "13901234567"
      responses:
        200:
          description: 操作成功完成
        400:
          description: 数据模型验证失败，响应的body中包含模型验证错误信息
        422:
          description: 数据模型有效，但在创建用户过程中出现了错误
          schema:
            type: object
            required:
              - errorCode
              - message
            properties:
              errorCode:
                description: 错误码
                type: integer
                example: 1
              message:
                description: 错误消息
                type: string
                example: 用户名冲突

  /users/{username}:
    get:
      summary: 获取用户信息
      description: 获取用户信息
      tags:
        - users
      produces:
        - application/json
      parameters:
        - in: path
          name: username
          type: string
          required: true
          description: 用户名
      responses:
        200:
          description: 操作成功完成
          schema:
            type: object
            required:
              - username
              - joinTime
              - totalSubmissions
              - totalAccepted
              - totalProblemsAttempted
              - totalProblemsAccepted
            properties:
              username:
                type: string
                description: 用户名
                example: Lancern
              joinTime:
                type: string
                description: 用户加入 BITOJ 的时间，时区为 UTC 时区
                example: "2019-9-24T10:00:00"
              totalSubmissions:
                type: integer
                description: 用户总提交数量
                example: 10
              totalAccepted:
                type: integer
                description: 用户总 AC 提交数量
                example: 3
              totalProblemsAttempted:
                type: integer
                description: 用户总共尝试的题目数量
                example: 2
              totalProblemsAccepted:
                type: integer
                description: 用户总 AC 题目数量
                example: 1
        404:
          description: 用户名未找到

  /auth:
    post:
      summary: 创建用户身份验证标识
      tags:
        - auth
      description: 创建用户身份验证标识
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: data
          required: true
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
                description: 用户名
                example: Lancern
              password:
                type: string
                description: 密码
                example: "hello_world"
      responses:
        200:
          description: 操作成功完成
          schema:
            type: object
            required:
              - username
              - isAdmin
              - jwt
            properties:
              username:
                type: string
                description: 用户名
                example: Lancern
              isAdmin:
                type: boolean
                description: 用户是否为管理员
                example: true
              jwt:
                type: string
                description: 编码用户身份验证信息的 JWT
        400:
          description: 数据模型验证失败
        422:
          description: 数据模型验证成功，但在执行用户身份验证时出现错误
          schema:
            type: object
            required:
              - errorCode
              - message
            properties:
              errorCode:
                type: integer
                description: 错误代码
                example: 1
              message:
                type: string
                description: 错误消息
                example: 用户不存在

